/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TorneosRouteImport } from './routes/torneos'
import { Route as SalasRouteImport } from './routes/salas'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as AmigosRouteImport } from './routes/amigos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JuegosSlugRouteImport } from './routes/juegos.$slug'

const TorneosRoute = TorneosRouteImport.update({
  id: '/torneos',
  path: '/torneos',
  getParentRoute: () => rootRouteImport,
} as any)
const SalasRoute = SalasRouteImport.update({
  id: '/salas',
  path: '/salas',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const AmigosRoute = AmigosRouteImport.update({
  id: '/amigos',
  path: '/amigos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JuegosSlugRoute = JuegosSlugRouteImport.update({
  id: '/juegos/$slug',
  path: '/juegos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/amigos': typeof AmigosRoute
  '/rankings': typeof RankingsRoute
  '/salas': typeof SalasRoute
  '/torneos': typeof TorneosRoute
  '/juegos/$slug': typeof JuegosSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/amigos': typeof AmigosRoute
  '/rankings': typeof RankingsRoute
  '/salas': typeof SalasRoute
  '/torneos': typeof TorneosRoute
  '/juegos/$slug': typeof JuegosSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/amigos': typeof AmigosRoute
  '/rankings': typeof RankingsRoute
  '/salas': typeof SalasRoute
  '/torneos': typeof TorneosRoute
  '/juegos/$slug': typeof JuegosSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/amigos' | '/rankings' | '/salas' | '/torneos' | '/juegos/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/amigos' | '/rankings' | '/salas' | '/torneos' | '/juegos/$slug'
  id:
    | '__root__'
    | '/'
    | '/amigos'
    | '/rankings'
    | '/salas'
    | '/torneos'
    | '/juegos/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AmigosRoute: typeof AmigosRoute
  RankingsRoute: typeof RankingsRoute
  SalasRoute: typeof SalasRoute
  TorneosRoute: typeof TorneosRoute
  JuegosSlugRoute: typeof JuegosSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/torneos': {
      id: '/torneos'
      path: '/torneos'
      fullPath: '/torneos'
      preLoaderRoute: typeof TorneosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salas': {
      id: '/salas'
      path: '/salas'
      fullPath: '/salas'
      preLoaderRoute: typeof SalasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amigos': {
      id: '/amigos'
      path: '/amigos'
      fullPath: '/amigos'
      preLoaderRoute: typeof AmigosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/juegos/$slug': {
      id: '/juegos/$slug'
      path: '/juegos/$slug'
      fullPath: '/juegos/$slug'
      preLoaderRoute: typeof JuegosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AmigosRoute: AmigosRoute,
  RankingsRoute: RankingsRoute,
  SalasRoute: SalasRoute,
  TorneosRoute: TorneosRoute,
  JuegosSlugRoute: JuegosSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
