/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RestablecerRouteImport } from './routes/restablecer'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as RecuperarRouteImport } from './routes/recuperar'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppTorneosRouteImport } from './routes/_app.torneos'
import { Route as AppSalasRouteImport } from './routes/_app.salas'
import { Route as AppRankingsRouteImport } from './routes/_app.rankings'
import { Route as AppPerfilRouteImport } from './routes/_app.perfil'
import { Route as AppAmigosRouteImport } from './routes/_app.amigos'
import { Route as AppSalaCodeRouteImport } from './routes/_app.sala.$code'
import { Route as AppPartidaIdRouteImport } from './routes/_app.partida.$id'
import { Route as AppJuegosSlugRouteImport } from './routes/_app.juegos.$slug'

const RestablecerRoute = RestablecerRouteImport.update({
  id: '/restablecer',
  path: '/restablecer',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarRoute = RecuperarRouteImport.update({
  id: '/recuperar',
  path: '/recuperar',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTorneosRoute = AppTorneosRouteImport.update({
  id: '/torneos',
  path: '/torneos',
  getParentRoute: () => AppRoute,
} as any)
const AppSalasRoute = AppSalasRouteImport.update({
  id: '/salas',
  path: '/salas',
  getParentRoute: () => AppRoute,
} as any)
const AppRankingsRoute = AppRankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppAmigosRoute = AppAmigosRouteImport.update({
  id: '/amigos',
  path: '/amigos',
  getParentRoute: () => AppRoute,
} as any)
const AppSalaCodeRoute = AppSalaCodeRouteImport.update({
  id: '/sala/$code',
  path: '/sala/$code',
  getParentRoute: () => AppRoute,
} as any)
const AppPartidaIdRoute = AppPartidaIdRouteImport.update({
  id: '/partida/$id',
  path: '/partida/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppJuegosSlugRoute = AppJuegosSlugRouteImport.update({
  id: '/juegos/$slug',
  path: '/juegos/$slug',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/recuperar': typeof RecuperarRoute
  '/registro': typeof RegistroRoute
  '/restablecer': typeof RestablecerRoute
  '/amigos': typeof AppAmigosRoute
  '/perfil': typeof AppPerfilRoute
  '/rankings': typeof AppRankingsRoute
  '/salas': typeof AppSalasRoute
  '/torneos': typeof AppTorneosRoute
  '/juegos/$slug': typeof AppJuegosSlugRoute
  '/partida/$id': typeof AppPartidaIdRoute
  '/sala/$code': typeof AppSalaCodeRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recuperar': typeof RecuperarRoute
  '/registro': typeof RegistroRoute
  '/restablecer': typeof RestablecerRoute
  '/amigos': typeof AppAmigosRoute
  '/perfil': typeof AppPerfilRoute
  '/rankings': typeof AppRankingsRoute
  '/salas': typeof AppSalasRoute
  '/torneos': typeof AppTorneosRoute
  '/': typeof AppIndexRoute
  '/juegos/$slug': typeof AppJuegosSlugRoute
  '/partida/$id': typeof AppPartidaIdRoute
  '/sala/$code': typeof AppSalaCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/recuperar': typeof RecuperarRoute
  '/registro': typeof RegistroRoute
  '/restablecer': typeof RestablecerRoute
  '/_app/amigos': typeof AppAmigosRoute
  '/_app/perfil': typeof AppPerfilRoute
  '/_app/rankings': typeof AppRankingsRoute
  '/_app/salas': typeof AppSalasRoute
  '/_app/torneos': typeof AppTorneosRoute
  '/_app/': typeof AppIndexRoute
  '/_app/juegos/$slug': typeof AppJuegosSlugRoute
  '/_app/partida/$id': typeof AppPartidaIdRoute
  '/_app/sala/$code': typeof AppSalaCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recuperar'
    | '/registro'
    | '/restablecer'
    | '/amigos'
    | '/perfil'
    | '/rankings'
    | '/salas'
    | '/torneos'
    | '/juegos/$slug'
    | '/partida/$id'
    | '/sala/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recuperar'
    | '/registro'
    | '/restablecer'
    | '/amigos'
    | '/perfil'
    | '/rankings'
    | '/salas'
    | '/torneos'
    | '/'
    | '/juegos/$slug'
    | '/partida/$id'
    | '/sala/$code'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/recuperar'
    | '/registro'
    | '/restablecer'
    | '/_app/amigos'
    | '/_app/perfil'
    | '/_app/rankings'
    | '/_app/salas'
    | '/_app/torneos'
    | '/_app/'
    | '/_app/juegos/$slug'
    | '/_app/partida/$id'
    | '/_app/sala/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecuperarRoute: typeof RecuperarRoute
  RegistroRoute: typeof RegistroRoute
  RestablecerRoute: typeof RestablecerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/restablecer': {
      id: '/restablecer'
      path: '/restablecer'
      fullPath: '/restablecer'
      preLoaderRoute: typeof RestablecerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar': {
      id: '/recuperar'
      path: '/recuperar'
      fullPath: '/recuperar'
      preLoaderRoute: typeof RecuperarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/torneos': {
      id: '/_app/torneos'
      path: '/torneos'
      fullPath: '/torneos'
      preLoaderRoute: typeof AppTorneosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/salas': {
      id: '/_app/salas'
      path: '/salas'
      fullPath: '/salas'
      preLoaderRoute: typeof AppSalasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rankings': {
      id: '/_app/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof AppRankingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil': {
      id: '/_app/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/amigos': {
      id: '/_app/amigos'
      path: '/amigos'
      fullPath: '/amigos'
      preLoaderRoute: typeof AppAmigosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sala/$code': {
      id: '/_app/sala/$code'
      path: '/sala/$code'
      fullPath: '/sala/$code'
      preLoaderRoute: typeof AppSalaCodeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/partida/$id': {
      id: '/_app/partida/$id'
      path: '/partida/$id'
      fullPath: '/partida/$id'
      preLoaderRoute: typeof AppPartidaIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/juegos/$slug': {
      id: '/_app/juegos/$slug'
      path: '/juegos/$slug'
      fullPath: '/juegos/$slug'
      preLoaderRoute: typeof AppJuegosSlugRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAmigosRoute: typeof AppAmigosRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppRankingsRoute: typeof AppRankingsRoute
  AppSalasRoute: typeof AppSalasRoute
  AppTorneosRoute: typeof AppTorneosRoute
  AppIndexRoute: typeof AppIndexRoute
  AppJuegosSlugRoute: typeof AppJuegosSlugRoute
  AppPartidaIdRoute: typeof AppPartidaIdRoute
  AppSalaCodeRoute: typeof AppSalaCodeRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAmigosRoute: AppAmigosRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppRankingsRoute: AppRankingsRoute,
  AppSalasRoute: AppSalasRoute,
  AppTorneosRoute: AppTorneosRoute,
  AppIndexRoute: AppIndexRoute,
  AppJuegosSlugRoute: AppJuegosSlugRoute,
  AppPartidaIdRoute: AppPartidaIdRoute,
  AppSalaCodeRoute: AppSalaCodeRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RecuperarRoute: RecuperarRoute,
  RegistroRoute: RegistroRoute,
  RestablecerRoute: RestablecerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
